image: node

# Cache node dependencies across all branches and jobs
cache:
    key: one-key-to-rule-them-all
    paths:
        - node_modules/

stages:
    - build
    - deploy

yarn-build:
    stage: build
    script:
        - yarn install
        - yarn test
        - yarn build
    artifacts:
        paths: 
            - build/

docker-build:
    only: [dev, master]
    stage: deploy
    image: docker
    variables:
        DOCKER_DRIVER: overlay2
    services:
        - docker:dind
    tags: [dind]
    before_script:
        - docker info
        - docker login -u $DOCKER_USER -p $DOCKER_PSW       
    script:
        - docker build ./ -t $DOCKER_USER/sa4-sphinx-frontend:latest
        - docker push $DOCKER_USER/sa4-sphinx-frontend
