image: node

stages:
    - install
    - test
    - build
    - deploy

yarn-install:
    stage: install
    script:
        - yarn install
    artifacts:
        paths: [node_modules/]

yarn-test:
    stage: test
    script:
        - pwd # cannot have an empty job
        #- yarn test

yarn-build:
    stage: build
    script:
        - yarn build
    artifacts:
        paths: [build/]

docker-build:
    stage: deploy
    image: docker:19.03.1
    variables:
        DOCKER_TLS_CERTDIR: ""
    services:
        - docker:19.03.1-dind
    tags: [dind]
    before_script:
        - docker info
        - docker login -u $DOCKER_USER -p $DOCKER_PSW       
    script:
        - docker build ./ -t $DOCKER_USER/sa4-sphinx:frontend
        - docker push $DOCKER_USER/sa4-sphinx:frontend