image: cypress/base

# Cache yarn and cypress across all branches and jobs
cache:
    key: frontend-cache
    paths:
        - /root/.cache

stages:
    - build
    - deploy

yarn-build:
    stage: build
    script:
        - yarn install
        - yarn ci-test
        - yarn build
    artifacts:
        paths: 
            - build/

docker-build:
    only: [dev, master]
    stage: deploy
    image: docker
    variables:
        DOCKER_DRIVER: overlay2
    services:
        - docker:dind
    tags: [dind]
    before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PSW
    script:
        - docker build ./ -t $DOCKER_USER/sa4-sphinx-frontend:latest
        - docker push $DOCKER_USER/sa4-sphinx-frontend:latest

docker-build-tags:
    only: [tags]
    stage: deploy
    image: docker
    variables:
        DOCKER_DRIVER: overlay2
    services:
        - docker:dind
    tags: [dind]
    before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PSW
    script:
        - docker build ./ -t $DOCKER_USER/sa4-sphinx-frontend:$CI_COMMIT_REF_NAME
        - docker push $DOCKER_USER/sa4-sphinx-frontend:$CI_COMMIT_REF_NAME