image: node

stages:
    - install
    - test
    - build
    - deploy

yarn-install:
    stage: install
    script:
        - yarn install
    artifacts:
        paths: [node_modules/]

yarn-test:
    stage: test
    script:
        - pwd # cannot have an empty job
        #- yarn test

yarn-build:
    stage: build
    script:
        - yarn build
    artifacts:
        paths: [build/]

docker-build:
    stage: deploy
    image: docker:dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
        DOCKER_DRIVER: overlay2
    services:
        - docker:dind
    tags: [dind]
    before_script:
        - docker info
        - docker login -u $DOCKER_USER -p $DOCKER_PSW       
    script:
        - docker build ./ -t steeven9/sa4-sphinx:frontend
        - docker push steeven9/sa4-sphinx:frontend